version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: astrology-ai-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: astrology_ai
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - astrology-ai-network

  client:
    build:
      context: .
      dockerfile: client/Dockerfile.dev
    container_name: astrology-ai-client
    volumes:
      - ./client:/app/client
      - ./shared:/app/shared
      - /app/client/node_modules
      - /app/shared/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - server
    env_file:
      - ./client/.env
    networks:
      - astrology-ai-network

  server:
    build:
      context: .
      dockerfile: server/Dockerfile.dev
    container_name: astrology-ai-server
    volumes:
      - ./server:/app/server
      - ./shared:/app/shared
      - /app/server/node_modules
      - /app/shared/node_modules
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    env_file:
      - ./server/.env
    networks:
      - astrology-ai-network

networks:
  astrology-ai-network:
    driver: bridge

volumes:
  postgres-data: